/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei';
import React from 'react';
import { Group } from 'three';

export const Model = React.forwardRef<Group>((props, ref) => {
  const { nodes, materials } = useGLTF('/models/SingleTulip.gltf');
  return (
    <group {...props} ref={ref} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16788.geometry}
        material={materials.Phong_8AB600}
        position={[0.05, -0.29, -0.22]}
        rotation={[2.17, 0.11, -1.27]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16785.geometry}
        material={materials.Phong_8AB600}
        position={[-0.07, -0.34, -0.07]}
        rotation={[1.64, -0.23, -1.23]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16778.geometry}
        material={materials.Phong_8AB600}
        position={[0.03, -0.06, -0.1]}
        rotation={[1.89, -0.19, -2.23]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16770.geometry}
        material={materials.Phong_8AB600}
        position={[-0.06, -0.08, 0.05]}
        rotation={[1.19, -0.11, 0.06]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16769.geometry}
        material={materials.Phong_8AB600}
        position={[-0.07, -0.03, -0.07]}
        rotation={[1.38, -0.44, 2.11]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16768.geometry}
        material={materials.Phong_8AB600}
        position={[0.06, -0.07, 0.01]}
        rotation={[1.67, 0.4, -0.72]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16766.geometry}
        material={materials.Phong_8AB600}
        position={[-0.03, -0.32, -0.05]}
        rotation={[1.66, -0.07, -2.02]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16754.geometry}
        material={materials.Phong_8AB600}
        position={[0.03, -0.03, -0.1]}
        rotation={[1.84, -0.13, -2.47]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16753.geometry}
        material={materials.Phong_8AB600}
        position={[0.04, -0.34, -0.02]}
        rotation={[1.54, 0.18, -0.44]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16723.geometry}
        material={materials.Phong_8AB600}
        position={[0.06, -0.36, -0.05]}
        rotation={[1.69, 0.16, 0.33]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16705.geometry}
        material={materials.Phong_8AB600}
        position={[0.19, -0.26, -0.22]}
        rotation={[2.26, 0.48, -0.71]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16702.geometry}
        material={materials.Phong_8AB600}
        position={[0, -0.33, -0.18]}
        rotation={[2.01, -0.1, -0.59]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16695.geometry}
        material={materials.Phong_8AB600}
        position={[0.09, -0.06, -0.08]}
        rotation={[2.18, 0.08, -1.64]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16687.geometry}
        material={materials.Phong_8AB600}
        position={[-0.08, -0.1, -0.02]}
        rotation={[1.57, -0.27, 0.69]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16686.geometry}
        material={materials.Phong_8AB600}
        position={[-0.01, -0.02, -0.11]}
        rotation={[1.94, -0.41, 2.82]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16685.geometry}
        material={materials.Phong_8AB600}
        position={[0.05, -0.1, 0.03]}
        rotation={[1.64, 0.42, -0.02]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16683.geometry}
        material={materials.Phong_8AB600}
        position={[0.02, -0.32, -0.13]}
        rotation={[1.92, 0.04, -1.38]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16671.geometry}
        material={materials.Phong_8AB600}
        position={[0.08, -0.03, -0.07]}
        rotation={[2.11, 0.09, -1.87]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16670.geometry}
        material={materials.Phong_8AB600}
        position={[0.06, -0.35, -0.08]}
        rotation={[1.68, 0.18, 0.21]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16640.geometry}
        material={materials.Phong_8AB600}
        position={[0.09, -0.37, -0.1]}
        rotation={[1.82, 0.24, 0.98]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16622.geometry}
        material={materials.Phong_8AB600}
        position={[0.15, -0.22, -0.27]}
        rotation={[2.46, 0.34, -1.61]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16619.geometry}
        material={materials.Phong_8AB600}
        position={[0.07, -0.33, -0.12]}
        rotation={[1.84, 0.14, -1.39]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16612.geometry}
        material={materials.Phong_8AB600}
        position={[0.06, -0.03, -0.1]}
        rotation={[2.09, 0.13, -2.47]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16604.geometry}
        material={materials.Phong_8AB600}
        position={[0, -0.11, 0.05]}
        rotation={[1.4, 0.29, 0.07]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16603.geometry}
        material={materials.Phong_8AB600}
        position={[-0.05, -0.05, -0.06]}
        rotation={[1.57, -0.04, 2.05]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16602.geometry}
        material={materials.Phong_8AB600}
        position={[0.11, -0.05, 0.01]}
        rotation={[2.01, 0.75, -0.96]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16600.geometry}
        material={materials.Phong_8AB600}
        position={[0.11, -0.3, -0.1]}
        rotation={[1.88, 0.29, -2.19]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16588.geometry}
        material={materials.Phong_8AB600}
        position={[0.04, -0.01, -0.09]}
        rotation={[2.05, 0.2, -2.7]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16587.geometry}
        material={materials.Phong_8AB600}
        position={[0.18, -0.3, -0.08]}
        rotation={[1.81, 0.56, -0.59]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16557.geometry}
        material={materials.Phong_8AB600}
        position={[0.2, -0.31, -0.12]}
        rotation={[1.97, 0.51, 0.12]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16376.geometry}
        material={materials.Phong_8AB600}
        position={[0.06, -0.07, 0.01]}
        rotation={[1.66, 0.4, -0.72]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16370.geometry}
        material={materials.Phong_8AB600}
        position={[0.04, -0.34, -0.02]}
        rotation={[1.54, 0.18, -0.44]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16344.geometry}
        material={materials.Phong_8AB600}
        position={[-0.07, -0.34, -0.07]}
        rotation={[1.63, -0.23, -1.22]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16341.geometry}
        material={materials.Phong_8AB600}
        position={[-0.07, -0.03, -0.07]}
        rotation={[1.38, -0.44, 2.11]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16336.geometry}
        material={materials.Phong_8AB600}
        position={[0.03, -0.06, -0.1]}
        rotation={[1.89, -0.19, -2.22]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16319.geometry}
        material={materials.Phong_8AB600}
        position={[-0.03, -0.32, -0.05]}
        rotation={[1.65, -0.07, -2.01]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16316.geometry}
        material={materials.Phong_8AB600}
        position={[0.05, -0.36, -0.05]}
        rotation={[1.69, 0.16, 0.33]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16300.geometry}
        material={materials.Phong_8AB600}
        position={[-0.06, -0.08, 0.05]}
        rotation={[1.18, -0.11, 0.06]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16293.geometry}
        material={materials.Phong_8AB600}
        position={[0.02, -0.03, -0.1]}
        rotation={[1.83, -0.13, -2.47]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.s16213.geometry}
        material={materials.Phong_8AB600}
        position={[0.05, -0.29, -0.22]}
        rotation={[2.16, 0.11, -1.27]}
        scale={0.97}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.r16266.geometry}
        material={materials.Reflective_FFFFFF}
        position={[0.01, -0.22, -0.01]}
        rotation={[0.01, 0.21, -3.13]}
        scale={0.86}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16799.geometry}
        material={materials.Phong_8AB600}
        position={[-0.01, 0.05, -0.02]}
        rotation={[1.86, 0.06, 0.46]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16798.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.06, 0.32, -0.19]}
        rotation={[0.75, -0.09, 0.67]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16797.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.35, 0.1]}
        rotation={[1.61, 0.81, 0.12]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16796.geometry}
        material={materials.Phong_FAF14C}
        position={[0.18, 0.2, 0.01]}
        rotation={[2.2, -0.19, -2.09]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16795.geometry}
        material={materials.Phong_8AB600}
        position={[0.05, 0.1, -0.02]}
        rotation={[1.13, -0.86, -2.32]}
        scale={0.34}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16794.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.35, 0.09]}
        rotation={[2.99, -0.06, -2.67]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16793.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.35, 0.1]}
        rotation={[1.58, 0.25, 0.76]}
        scale={0.28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16792.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.09, 0.33, 0.01]}
        rotation={[1.07, 0.51, -0.19]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16791.geometry}
        material={materials.Phong_8AB600}
        position={[-0.01, 0.14, -0.04]}
        rotation={[2.23, 0.43, 0.32]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16790.geometry}
        material={materials.Phong_E4BD17}
        position={[0.18, 0.21, 0]}
        rotation={[2.21, -0.05, -1.43]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16789.geometry}
        material={materials.Phong_FBF058}
        position={[0, 0.35, 0.1]}
        rotation={[2.72, -0.17, -3.07]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16787.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.09, 0.35, 0.02]}
        rotation={[1.54, -0.34, -2.79]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16786.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.09, 0.33, 0.02]}
        rotation={[1.61, 0.46, -1.41]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16784.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.06, 0.33, -0.19]}
        rotation={[1.93, 0.09, -1.93]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16783.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.08, 0.34, 0.02]}
        rotation={[0.91, -0.18, 1.5]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16782.geometry}
        material={materials.Phong_FBF058}
        position={[-0.07, 0.34, -0.11]}
        rotation={[1.77, 0.43, -0.99]}
        scale={0.28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16781.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.34, 0.1]}
        rotation={[1.57, -0.41, 1.62]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16780.geometry}
        material={materials.Phong_E4BD17}
        position={[0.12, 0.3, -0.05]}
        rotation={[2.38, -0.35, -2.32]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16779.geometry}
        material={materials.Phong_E4BD17}
        position={[0.13, 0.31, -0.05]}
        rotation={[1.55, 0.26, 0.64]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16777.geometry}
        material={materials.Phong_8AB600}
        position={[-0.02, 0.14, -0.06]}
        rotation={[1.53, -0.3, -1.96]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16776.geometry}
        material={materials.Phong_FBF058}
        position={[-0.06, 0.34, -0.1]}
        rotation={[0.91, 0.42, 0.26]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16775.geometry}
        material={materials.Phong_FAF14C}
        position={[0.13, 0.3, -0.06]}
        rotation={[1.21, 0.15, 0.5]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16774.geometry}
        material={materials.Phong_FBF058}
        position={[0.09, 0.29, -0.16]}
        rotation={[1.51, 0.32, -0.94]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16773.geometry}
        material={materials.Phong_E4BD17}
        position={[0.07, 0.28, 0.04]}
        rotation={[2.02, -0.95, 2.61]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16772.geometry}
        material={materials.Phong_FBF058}
        position={[0.09, 0.29, 0.03]}
        rotation={[1.14, 0.03, 0.66]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16771.geometry}
        material={materials.Phong_FAF14C}
        position={[0.12, 0.3, -0.06]}
        rotation={[2.2, 0.3, -1.38]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16767.geometry}
        material={materials.Phong_8AB600}
        position={[0.04, 0.13, 0.02]}
        rotation={[1.74, 0.02, 1.38]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16765.geometry}
        material={materials.Phong_FBF058}
        position={[-0.07, 0.34, -0.11]}
        rotation={[2.34, 0.25, -1.81]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16764.geometry}
        material={materials.Phong_FBF058}
        position={[-0.06, 0.33, -0.09]}
        rotation={[1.16, -0.64, 2.38]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16763.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.06, 0.33, -0.18]}
        rotation={[0.68, -0.22, 1.31]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16762.geometry}
        material={materials.Phong_FBF058}
        position={[0.03, 0.31, -0.13]}
        rotation={[1.37, 0.67, -0.24]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16761.geometry}
        material={materials.Phong_698A1F}
        position={[0.05, 0.16, -0.03]}
        rotation={[1.72, -0.98, -0.77]}
        scale={0.37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16760.geometry}
        material={materials.Phong_FAF14C}
        position={[0.01, 0.3, -0.19]}
        rotation={[0.99, -0.58, 1.81]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16759.geometry}
        material={materials.Phong_FAF14C}
        position={[0.01, 0.3, -0.2]}
        rotation={[0.78, -0.14, 0.77]}
        scale={0.34}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16758.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.07, 0.34, -0.19]}
        rotation={[1.72, -0.19, -1.74]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16757.geometry}
        material={materials.Phong_FBF058}
        position={[0.03, 0.31, -0.12]}
        rotation={[2.2, -0.5, -2.77]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16756.geometry}
        material={materials.Phong_FBF058}
        position={[-0.05, 0.33, -0.09]}
        rotation={[0.89, -0.4, 1.73]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16755.geometry}
        material={materials.Phong_78AC41}
        position={[0.02, 0.14, -0.08]}
        rotation={[1.51, -0.36, -1.05]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16752.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.06, 0.33, -0.18]}
        rotation={[1.24, -0.64, 2.53]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16751.geometry}
        material={materials.Phong_FBF058}
        position={[-0.06, 0.33, -0.1]}
        rotation={[1.91, -0.14, -3.03]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16750.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.09, 0.33, 0.01]}
        rotation={[1.85, -0.25, -2.8]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16749.geometry}
        material={materials.Phong_FAF14C}
        position={[0.01, 0.3, -0.2]}
        rotation={[1.27, 0.45, -0.67]}
        scale={0.33}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16748.geometry}
        material={materials.Phong_FAF14C}
        position={[0.18, 0.2, 0.01]}
        rotation={[2.02, -0.65, -3.13]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16747.geometry}
        material={materials.Phong_E4BD17}
        position={[0.01, 0.31, -0.21]}
        rotation={[1.54, 0.13, -0.64]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16746.geometry}
        material={materials.Phong_8AB600}
        position={[0.05, 0.13, -0.09]}
        rotation={[1.46, -0.46, -0.43]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16745.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.01, 0.3, -0.2]}
        rotation={[1.71, -0.57, -2.66]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16744.geometry}
        material={materials.Phong_FBF058}
        position={[0.02, 0.32, -0.13]}
        rotation={[2.43, -0.31, -2.3]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16743.geometry}
        material={materials.Phong_FBF058}
        position={[0.02, 0.31, -0.12]}
        rotation={[1.15, 0.15, 0.48]}
        scale={0.28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16742.geometry}
        material={materials.Phong_E4BD17}
        position={[0.19, 0.22, 0.01]}
        rotation={[1.21, -0.29, 1.39]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16741.geometry}
        material={materials.Phong_FAF14C}
        position={[0.18, 0.21, 0]}
        rotation={[1.59, 0.21, -0.43]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16740.geometry}
        material={materials.Phong_8AB600}
        position={[0.03, 0.1, -0.02]}
        rotation={[1.72, -0.54, -0.97]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16739.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.34, 0.1]}
        rotation={[2.29, 0.57, -1.44]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16738.geometry}
        material={materials.Phong_FBF058}
        position={[0.08, 0.29, 0.03]}
        rotation={[1.75, 0.4, -0.48]}
        scale={0.45}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16737.geometry}
        material={materials.Phong_FBF058}
        position={[0.1, 0.3, 0.03]}
        rotation={[2.46, 0.41, -1.29]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16736.geometry}
        material={materials.Phong_FBF058}
        position={[0.02, 0.3, -0.12]}
        rotation={[0.95, -0.48, 1.29]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16735.geometry}
        material={materials.Phong_E4BD17}
        position={[0.08, 0.29, 0.03]}
        rotation={[1.42, -0.46, 1.35]}
        scale={0.32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16734.geometry}
        material={materials.Phong_FBF058}
        position={[0.09, 0.3, -0.16]}
        rotation={[2.08, -0.98, -2.52]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16733.geometry}
        material={materials.Phong_8AB600}
        position={[-0.04, 0.14, -0.06]}
        rotation={[1.43, 0.26, 1.65]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16732.geometry}
        material={materials.Phong_FBF058}
        position={[0.09, 0.29, -0.15]}
        rotation={[1.44, -1.19, 2.66]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16731.geometry}
        material={materials.Phong_FBF058}
        position={[0.08, 0.29, -0.16]}
        rotation={[1.9, -0.27, -1.95]}
        scale={0.45}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16730.geometry}
        material={materials.Phong_78AC41}
        position={[0.02, 0.11, -0.01]}
        rotation={[1.96, 0.04, 0.44]}
        scale={0.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16729.geometry}
        material={materials.Phong_FBF058}
        position={[0.08, 0.29, 0.03]}
        rotation={[2.65, 0.1, -1.87]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16728.geometry}
        material={materials.Phong_FAF14C}
        position={[0.13, 0.29, -0.05]}
        rotation={[2.25, -0.42, -3.03]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16727.geometry}
        material={materials.Phong_FAF14C}
        position={[0.18, 0.21, 0.01]}
        rotation={[1, -0.58, 1.08]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16726.geometry}
        material={materials.Phong_FBF058}
        position={[0.09, 0.29, -0.14]}
        rotation={[0.45, -0.3, 0.56]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16725.geometry}
        material={materials.Phong_FBF058}
        position={[0.03, 0.3, -0.12]}
        rotation={[1.88, 0.31, -1.6]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16724.geometry}
        material={materials.Phong_FBF058}
        position={[0.09, 0.29, -0.15]}
        rotation={[1.02, 0.05, -0.22]}
        scale={0.32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16722.geometry}
        material={materials.Phong_FAF14C}
        position={[0.13, 0.29, -0.06]}
        rotation={[1.72, -0.53, 2.04]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16721.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.08, 0.34, 0.01]}
        rotation={[0.91, 0.47, 0.54]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16720.geometry}
        material={materials.Phong_8AB600}
        position={[0.02, 0.09, -0.04]}
        rotation={[1.21, -0.72, -1.92]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16719.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.06, 0.33, -0.19]}
        rotation={[1.21, 0.32, -0.42]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16718.geometry}
        material={materials.Phong_E4BD17}
        position={[0, 0.3, -0.2]}
        rotation={[1.09, -0.81, 2.48]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16717.geometry}
        material={materials.Phong_8AB600}
        position={[-0.03, 0.13, -0.07]}
        rotation={[0.72, -0.22, 2.33]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16716.geometry}
        material={materials.Phong_8AB600}
        position={[0, 0.04, -0.01]}
        rotation={[2.02, 0.27, 1.08]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16715.geometry}
        material={materials.Phong_FAF14C}
        position={[0.05, 0.34, -0.11]}
        rotation={[1.17, -0.5, 1.19]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16714.geometry}
        material={materials.Phong_FBF058}
        position={[-0.08, 0.3, 0.15]}
        rotation={[1.26, 0.68, 0.99]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16713.geometry}
        material={materials.Phong_FAF14C}
        position={[0.12, 0.16, 0.16]}
        rotation={[2.44, 0.23, -1.6]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16712.geometry}
        material={materials.Phong_8AB600}
        position={[0.05, 0.07, 0.03]}
        rotation={[2.17, -0.84, -1.32]}
        scale={0.34}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16711.geometry}
        material={materials.Phong_FBF058}
        position={[-0.08, 0.3, 0.15]}
        rotation={[-3.05, 0.58, -2.61]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16710.geometry}
        material={materials.Phong_FBF058}
        position={[-0.08, 0.3, 0.15]}
        rotation={[1.67, 0.25, 1.43]}
        scale={0.28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16709.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.09, 0.31, 0.03]}
        rotation={[1.12, 0.18, 0.4]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16708.geometry}
        material={materials.Phong_8AB600}
        position={[0.01, 0.12, -0.01]}
        rotation={[2.09, 0.77, 0.99]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16707.geometry}
        material={materials.Phong_E4BD17}
        position={[0.13, 0.17, 0.15]}
        rotation={[2.39, 0.37, -0.93]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16706.geometry}
        material={materials.Phong_FBF058}
        position={[-0.08, 0.29, 0.15]}
        rotation={[2.95, 0.43, -2.85]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16704.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.1, 0.32, 0.04]}
        rotation={[2, -0.24, -2.12]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16703.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.1, 0.31, 0.04]}
        rotation={[1.55, 0.43, -0.7]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16701.geometry}
        material={materials.Phong_FAF14C}
        position={[0.05, 0.34, -0.11]}
        rotation={[2.06, 0.33, -1.32]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16700.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.09, 0.31, 0.05]}
        rotation={[1.38, -0.49, 2.1]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16699.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.33, -0.04]}
        rotation={[1.69, 0.51, -0.27]}
        scale={0.28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16698.geometry}
        material={materials.Phong_FBF058}
        position={[-0.09, 0.29, 0.15]}
        rotation={[2.06, -0.28, 2.29]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16697.geometry}
        material={materials.Phong_E4BD17}
        position={[0.11, 0.27, 0.1]}
        rotation={[2.68, 0.16, -1.93]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16696.geometry}
        material={materials.Phong_E4BD17}
        position={[0.12, 0.28, 0.11]}
        rotation={[1.64, 0.24, 1.31]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16694.geometry}
        material={materials.Phong_8AB600}
        position={[0.02, 0.13, -0.03]}
        rotation={[1.96, -0.21, -1.3]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16693.geometry}
        material={materials.Phong_FBF058}
        position={[0, 0.33, -0.04]}
        rotation={[1.05, 0.03, 0.79]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16692.geometry}
        material={materials.Phong_FAF14C}
        position={[0.12, 0.27, 0.1]}
        rotation={[1.44, -0.04, 1.11]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16691.geometry}
        material={materials.Phong_FBF058}
        position={[0.16, 0.29, -0.01]}
        rotation={[1.57, 0.27, -0.26]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16690.geometry}
        material={materials.Phong_E4BD17}
        position={[0.02, 0.24, 0.13]}
        rotation={[2.71, -0.49, -3.04]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16689.geometry}
        material={materials.Phong_FBF058}
        position={[0.04, 0.24, 0.14]}
        rotation={[1.45, -0.19, 1.27]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16688.geometry}
        material={materials.Phong_FAF14C}
        position={[0.12, 0.27, 0.09]}
        rotation={[2.17, 0.66, -0.77]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16684.geometry}
        material={materials.Phong_8AB600}
        position={[0.01, 0.1, 0.06]}
        rotation={[1.94, 0.16, 2.01]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16682.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.34, -0.05]}
        rotation={[2.34, 0.69, -1.27]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16681.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.33, -0.03]}
        rotation={[1.94, -0.69, -3.08]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16680.geometry}
        material={materials.Phong_E4BD17}
        position={[0.05, 0.35, -0.1]}
        rotation={[1.18, -0.64, 1.86]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16679.geometry}
        material={materials.Phong_FBF058}
        position={[0.09, 0.31, -0.01]}
        rotation={[1.23, 0.46, 0.49]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16678.geometry}
        material={materials.Phong_698A1F}
        position={[0.05, 0.14, 0.04]}
        rotation={[2.59, -0.63, 0.04]}
        scale={0.37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16677.geometry}
        material={materials.Phong_FAF14C}
        position={[0.11, 0.31, -0.07]}
        rotation={[1.76, -0.75, 2.61]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16676.geometry}
        material={materials.Phong_FAF14C}
        position={[0.11, 0.31, -0.08]}
        rotation={[1.23, -0.52, 1.32]}
        scale={0.34}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16675.geometry}
        material={materials.Phong_E4BD17}
        position={[0.05, 0.36, -0.11]}
        rotation={[2.05, -0.01, -1.12]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16674.geometry}
        material={materials.Phong_FBF058}
        position={[0.08, 0.31, -0.01]}
        rotation={[2.59, -0.04, -2.29]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16673.geometry}
        material={materials.Phong_FBF058}
        position={[0, 0.33, -0.03]}
        rotation={[1.51, -0.67, 2.41]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16672.geometry}
        material={materials.Phong_78AC41}
        position={[0.06, 0.13, -0.02]}
        rotation={[1.98, -0.27, -0.38]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16669.geometry}
        material={materials.Phong_FAF14C}
        position={[0.04, 0.35, -0.1]}
        rotation={[2, -0.64, -2.95]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16668.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.33, -0.04]}
        rotation={[2.17, 0.13, -2.44]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16667.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.1, 0.31, 0.03]}
        rotation={[2.18, 0, -2.2]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16666.geometry}
        material={materials.Phong_FAF14C}
        position={[0.11, 0.31, -0.08]}
        rotation={[1.3, 0.23, -0.02]}
        scale={0.33}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16665.geometry}
        material={materials.Phong_FAF14C}
        position={[0.13, 0.15, 0.16]}
        rotation={[2.53, -0.24, -2.57]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16664.geometry}
        material={materials.Phong_E4BD17}
        position={[0.12, 0.32, -0.09]}
        rotation={[1.71, 0.13, 0.01]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16663.geometry}
        material={materials.Phong_8AB600}
        position={[0.08, 0.12, -0.01]}
        rotation={[2.02, -0.38, 0.27]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16662.geometry}
        material={materials.Phong_FAF14C}
        position={[0.1, 0.32, -0.09]}
        rotation={[2.26, -0.33, -1.99]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16661.geometry}
        material={materials.Phong_FBF058}
        position={[0.08, 0.31, -0.01]}
        rotation={[2.7, 0.22, -1.93]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16660.geometry}
        material={materials.Phong_FBF058}
        position={[0.08, 0.3, -0.01]}
        rotation={[1.39, -0.08, 1.08]}
        scale={0.28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16659.geometry}
        material={materials.Phong_E4BD17}
        position={[0.13, 0.17, 0.17]}
        rotation={[1.7, -0.4, 2.06]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16658.geometry}
        material={materials.Phong_FAF14C}
        position={[0.13, 0.16, 0.15]}
        rotation={[1.7, 0.23, 0.23]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16657.geometry}
        material={materials.Phong_8AB600}
        position={[0.04, 0.07, 0.02]}
        rotation={[2.25, -0.3, -0.31]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16656.geometry}
        material={materials.Phong_FBF058}
        position={[-0.08, 0.29, 0.15]}
        rotation={[2.02, 0.91, -0.69]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16655.geometry}
        material={materials.Phong_FBF058}
        position={[0.04, 0.24, 0.14]}
        rotation={[1.7, 0.47, 0.23]}
        scale={0.45}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16654.geometry}
        material={materials.Phong_FBF058}
        position={[0.04, 0.25, 0.15]}
        rotation={[2.36, 0.89, -0.73]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16653.geometry}
        material={materials.Phong_FBF058}
        position={[0.07, 0.3, -0.01]}
        rotation={[1.63, -0.7, 2.03]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16652.geometry}
        material={materials.Phong_E4BD17}
        position={[0.03, 0.24, 0.14]}
        rotation={[1.99, -0.41, 2.06]}
        scale={0.32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16651.geometry}
        material={materials.Phong_FBF058}
        position={[0.15, 0.3, -0.01]}
        rotation={[2.77, -0.5, -1.92]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16650.geometry}
        material={materials.Phong_8AB600}
        position={[0, 0.13, -0.04]}
        rotation={[1.54, 0.18, 2.3]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16649.geometry}
        material={materials.Phong_FBF058}
        position={[0.15, 0.28, 0]}
        rotation={[2.73, -0.86, -2.47]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16648.geometry}
        material={materials.Phong_FBF058}
        position={[0.15, 0.29, -0.01]}
        rotation={[2.23, 0.01, -1.37]}
        scale={0.45}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16647.geometry}
        material={materials.Phong_78AC41}
        position={[0.02, 0.09, 0.02]}
        rotation={[2.11, 0.31, 1.04]}
        scale={0.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16646.geometry}
        material={materials.Phong_FBF058}
        position={[0.03, 0.24, 0.14]}
        rotation={[2.78, 0.68, -1.55]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16645.geometry}
        material={materials.Phong_FAF14C}
        position={[0.12, 0.26, 0.1]}
        rotation={[2.6, 0.05, -2.58]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16644.geometry}
        material={materials.Phong_FAF14C}
        position={[0.13, 0.16, 0.16]}
        rotation={[1.76, -0.74, 1.88]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16643.geometry}
        material={materials.Phong_FBF058}
        position={[0.15, 0.28, 0.01]}
        rotation={[0.97, -0.82, 1.02]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16642.geometry}
        material={materials.Phong_FBF058}
        position={[0.08, 0.3, -0.01]}
        rotation={[1.87, 0.47, -0.93]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16641.geometry}
        material={materials.Phong_FBF058}
        position={[0.15, 0.29, 0]}
        rotation={[1.34, -0.24, 0.36]}
        scale={0.32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16639.geometry}
        material={materials.Phong_FAF14C}
        position={[0.13, 0.26, 0.1]}
        rotation={[2.25, -0.29, 2.7]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16638.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.09, 0.31, 0.04]}
        rotation={[1.02, 0.07, 1.07]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16637.geometry}
        material={materials.Phong_8AB600}
        position={[0.03, 0.07, 0]}
        rotation={[2.06, -0.71, -1.05]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16636.geometry}
        material={materials.Phong_FAF14C}
        position={[0.04, 0.34, -0.11]}
        rotation={[1.33, 0.09, 0.2]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16635.geometry}
        material={materials.Phong_E4BD17}
        position={[0.11, 0.32, -0.08]}
        rotation={[2.08, -0.83, -2.84]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16634.geometry}
        material={materials.Phong_8AB600}
        position={[0.01, 0.13, -0.04]}
        rotation={[1.21, -0.63, 2.88]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16633.geometry}
        material={materials.Phong_8AB600}
        position={[-0.01, 0.03, 0.01]}
        rotation={[2.13, 0.38, 0.21]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16632.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.18, 0.29, -0.1]}
        rotation={[0.95, 0.27, 0.85]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16631.geometry}
        material={materials.Phong_FBF058}
        position={[-0.1, 0.29, 0.19]}
        rotation={[2.13, 1.16, -0.25]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16630.geometry}
        material={materials.Phong_FAF14C}
        position={[0.11, 0.24, 0.06]}
        rotation={[2.38, 0.04, -2.42]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16629.geometry}
        material={materials.Phong_8AB600}
        position={[0.03, 0.1, 0.01]}
        rotation={[1.36, -0.46, -2.28]}
        scale={0.34}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16628.geometry}
        material={materials.Phong_FBF058}
        position={[-0.11, 0.29, 0.18]}
        rotation={[-3.12, -0.13, -3.07]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16627.geometry}
        material={materials.Phong_FBF058}
        position={[-0.11, 0.28, 0.19]}
        rotation={[1.86, 0.62, 0.59]}
        scale={0.28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16626.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.18, 0.25, 0.1]}
        rotation={[1.21, 0.91, -0.09]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16625.geometry}
        material={materials.Phong_8AB600}
        position={[-0.04, 0.12, 0]}
        rotation={[2.65, 0.61, -0.09]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16624.geometry}
        material={materials.Phong_E4BD17}
        position={[0.1, 0.25, 0.05]}
        rotation={[2.44, 0.17, -1.77]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16623.geometry}
        material={materials.Phong_FBF058}
        position={[-0.1, 0.28, 0.18]}
        rotation={[2.87, -0.13, 2.81]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16621.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.19, 0.26, 0.11]}
        rotation={[1.73, 0.05, -2.91]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16620.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.18, 0.25, 0.11]}
        rotation={[1.95, 0.82, -1.63]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16618.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.18, 0.29, -0.09]}
        rotation={[2.21, 0.39, -2.21]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16617.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.17, 0.26, 0.11]}
        rotation={[1.12, 0.2, 1.62]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16616.geometry}
        material={materials.Phong_FBF058}
        position={[-0.18, 0.28, -0.01]}
        rotation={[2.14, 0.76, -1.28]}
        scale={0.28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16615.geometry}
        material={materials.Phong_FBF058}
        position={[-0.1, 0.27, 0.19]}
        rotation={[1.75, -0.03, 1.48]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16614.geometry}
        material={materials.Phong_E4BD17}
        position={[0.01, 0.31, 0.02]}
        rotation={[2.49, -0.17, -2.69]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16613.geometry}
        material={materials.Phong_E4BD17}
        position={[0.02, 0.33, 0.02]}
        rotation={[1.83, 0.64, 0.48]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16611.geometry}
        material={materials.Phong_8AB600}
        position={[-0.06, 0.11, -0.02]}
        rotation={[1.73, 0.09, -2.08]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16610.geometry}
        material={materials.Phong_FBF058}
        position={[-0.17, 0.29, -0.01]}
        rotation={[1.02, 0.8, 0.44]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16609.geometry}
        material={materials.Phong_FAF14C}
        position={[0.02, 0.32, 0.02]}
        rotation={[1.42, 0.55, 0.5]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16608.geometry}
        material={materials.Phong_FBF058}
        position={[-0.03, 0.32, -0.09]}
        rotation={[1.8, 0.7, -1.08]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16607.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.01, 0.26, 0.11]}
        rotation={[1.98, -0.63, 2.26]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16606.geometry}
        material={materials.Phong_FBF058}
        position={[0, 0.28, 0.11]}
        rotation={[1.34, 0.43, 0.7]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16605.geometry}
        material={materials.Phong_FAF14C}
        position={[0.01, 0.31, 0.01]}
        rotation={[2.56, 0.5, -1.76]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16601.geometry}
        material={materials.Phong_8AB600}
        position={[0.01, 0.12, 0.06]}
        rotation={[1.99, 0.36, 1.17]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16599.geometry}
        material={materials.Phong_FBF058}
        position={[-0.18, 0.29, -0.02]}
        rotation={[2.68, 0.41, -2.2]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16598.geometry}
        material={materials.Phong_FBF058}
        position={[-0.17, 0.28, 0]}
        rotation={[1.38, -0.23, 2.41]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16597.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.18, 0.3, -0.09]}
        rotation={[0.9, 0.13, 1.52]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16596.geometry}
        material={materials.Phong_FBF058}
        position={[-0.08, 0.3, -0.04]}
        rotation={[1.67, 1.07, -0.36]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16595.geometry}
        material={materials.Phong_698A1F}
        position={[0, 0.16, 0.01]}
        rotation={[1.77, -0.61, -1]}
        scale={0.37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16594.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.1, 0.3, -0.11]}
        rotation={[1.23, -0.19, 1.9]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16593.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.11, 0.3, -0.12]}
        rotation={[0.98, 0.23, 0.94]}
        scale={0.34}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16592.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.19, 0.3, -0.1]}
        rotation={[1.93, 0.17, -1.93]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16591.geometry}
        material={materials.Phong_FBF058}
        position={[-0.09, 0.3, -0.04]}
        rotation={[2.28, -0.25, -3.11]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16590.geometry}
        material={materials.Phong_FBF058}
        position={[-0.16, 0.28, 0]}
        rotation={[1.13, -0.02, 1.86]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16589.geometry}
        material={materials.Phong_78AC41}
        position={[-0.02, 0.14, -0.04]}
        rotation={[1.7, 0.03, -1.16]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16586.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.18, 0.29, -0.08]}
        rotation={[1.45, -0.24, 2.52]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16585.geometry}
        material={materials.Phong_FBF058}
        position={[-0.17, 0.28, -0.01]}
        rotation={[2.12, 0.18, 3]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16584.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.18, 0.25, 0.11]}
        rotation={[2.04, 0.08, -3.03]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16583.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.1, 0.3, -0.11]}
        rotation={[1.5, 0.85, -0.69]}
        scale={0.33}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16582.geometry}
        material={materials.Phong_FAF14C}
        position={[0.12, 0.24, 0.06]}
        rotation={[2.09, -0.34, 2.85]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16581.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.11, 0.31, -0.13]}
        rotation={[1.79, 0.51, -0.78]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16580.geometry}
        material={materials.Phong_8AB600}
        position={[0.01, 0.14, -0.04]}
        rotation={[1.65, -0.07, -0.52]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16579.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.12, 0.29, -0.12]}
        rotation={[1.85, -0.2, -2.84]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16578.geometry}
        material={materials.Phong_FBF058}
        position={[-0.09, 0.31, -0.05]}
        rotation={[2.55, -0.14, -2.68]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16577.geometry}
        material={materials.Phong_FBF058}
        position={[-0.09, 0.3, -0.04]}
        rotation={[1.35, 0.55, 0.51]}
        scale={0.28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16576.geometry}
        material={materials.Phong_E4BD17}
        position={[0.12, 0.25, 0.06]}
        rotation={[1.42, 0.11, 1.39]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16575.geometry}
        material={materials.Phong_FAF14C}
        position={[0.11, 0.24, 0.04]}
        rotation={[1.87, 0.58, -0.6]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16574.geometry}
        material={materials.Phong_8AB600}
        position={[0.01, 0.09, 0.01]}
        rotation={[1.86, -0.17, -1.16]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16573.geometry}
        material={materials.Phong_FBF058}
        position={[-0.1, 0.28, 0.19]}
        rotation={[2.78, 0.71, -1.91]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16572.geometry}
        material={materials.Phong_FBF058}
        position={[0, 0.28, 0.1]}
        rotation={[2.11, 0.74, -0.75]}
        scale={0.45}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16571.geometry}
        material={materials.Phong_FBF058}
        position={[0, 0.29, 0.11]}
        rotation={[2.87, 0.51, -1.73]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16570.geometry}
        material={materials.Phong_FBF058}
        position={[-0.08, 0.29, -0.03]}
        rotation={[1.19, -0.09, 1.4]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16569.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.01, 0.27, 0.1]}
        rotation={[1.61, -0.07, 1.27]}
        scale={0.32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16568.geometry}
        material={materials.Phong_FBF058}
        position={[-0.03, 0.32, -0.08]}
        rotation={[2, -0.67, -2.91]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16567.geometry}
        material={materials.Phong_8AB600}
        position={[-0.07, 0.11, -0.01]}
        rotation={[1.69, 0.66, 1.55]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16566.geometry}
        material={materials.Phong_FBF058}
        position={[-0.03, 0.31, -0.07]}
        rotation={[1.55, -0.8, 2.54]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16565.geometry}
        material={materials.Phong_FBF058}
        position={[-0.03, 0.31, -0.08]}
        rotation={[2.08, 0.05, -2.2]}
        scale={0.45}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16564.geometry}
        material={materials.Phong_78AC41}
        position={[0, 0.1, 0.02]}
        rotation={[2.22, 0.33, 0.16]}
        scale={0.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16563.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.27, 0.11]}
        rotation={[2.91, 0.15, -2.27]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16562.geometry}
        material={materials.Phong_FAF14C}
        position={[0.02, 0.31, 0.02]}
        rotation={[2.35, -0.19, 2.91]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16561.geometry}
        material={materials.Phong_FAF14C}
        position={[0.11, 0.25, 0.06]}
        rotation={[1.24, -0.19, 1.17]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16560.geometry}
        material={materials.Phong_FBF058}
        position={[-0.02, 0.31, -0.07]}
        rotation={[0.71, -0.01, 0.84]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16559.geometry}
        material={materials.Phong_FBF058}
        position={[-0.08, 0.29, -0.04]}
        rotation={[2.22, 0.61, -1.9]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16558.geometry}
        material={materials.Phong_FBF058}
        position={[-0.03, 0.31, -0.08]}
        rotation={[1.21, 0.44, -0.13]}
        scale={0.32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16556.geometry}
        material={materials.Phong_FAF14C}
        position={[0.03, 0.31, 0.02]}
        rotation={[1.86, -0.16, 1.85]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16555.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.18, 0.26, 0.11]}
        rotation={[1, 0.85, 0.73]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16554.geometry}
        material={materials.Phong_8AB600}
        position={[0, 0.08, -0.01]}
        rotation={[1.42, -0.32, -1.91]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16553.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.18, 0.29, -0.09]}
        rotation={[1.41, 0.73, -0.41]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16552.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.11, 0.3, -0.12]}
        rotation={[1.33, -0.41, 2.53]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16551.geometry}
        material={materials.Phong_8AB600}
        position={[-0.06, 0.11, -0.02]}
        rotation={[0.93, 0.13, 2.52]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16382.geometry}
        material={materials.Phong_FAF14C}
        position={[0.13, 0.29, -0.06]}
        rotation={[1.71, -0.53, 2.05]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16381.geometry}
        material={materials.Phong_FAF14C}
        position={[0.12, 0.3, -0.06]}
        rotation={[2.2, 0.3, -1.37]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16380.geometry}
        material={materials.Phong_FAF14C}
        position={[0.13, 0.29, -0.05]}
        rotation={[2.25, -0.42, -3.02]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16379.geometry}
        material={materials.Phong_E4BD17}
        position={[0.12, 0.3, -0.05]}
        rotation={[2.38, -0.35, -2.32]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16378.geometry}
        material={materials.Phong_E4BD17}
        position={[0.13, 0.31, -0.05]}
        rotation={[1.55, 0.26, 0.64]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16377.geometry}
        material={materials.Phong_FAF14C}
        position={[0.13, 0.3, -0.06]}
        rotation={[1.21, 0.15, 0.5]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16375.geometry}
        material={materials.Phong_8AB600}
        position={[0.05, 0.1, -0.03]}
        rotation={[1.12, -0.86, -2.32]}
        scale={0.34}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16374.geometry}
        material={materials.Phong_8AB600}
        position={[-0.01, 0.05, -0.02]}
        rotation={[1.86, 0.06, 0.47]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16373.geometry}
        material={materials.Phong_8AB600}
        position={[0.03, 0.09, -0.02]}
        rotation={[1.72, -0.54, -0.97]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16372.geometry}
        material={materials.Phong_8AB600}
        position={[0.02, 0.09, -0.04]}
        rotation={[1.21, -0.72, -1.91]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16371.geometry}
        material={materials.Phong_FBF058}
        position={[0.03, 0.31, -0.13]}
        rotation={[1.36, 0.67, -0.23]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16369.geometry}
        material={materials.Phong_FBF058}
        position={[0.02, 0.32, -0.13]}
        rotation={[2.43, -0.3, -2.3]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16368.geometry}
        material={materials.Phong_FBF058}
        position={[0.02, 0.31, -0.13]}
        rotation={[2.2, -0.5, -2.76]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16367.geometry}
        material={materials.Phong_FBF058}
        position={[0.02, 0.31, -0.13]}
        rotation={[1.15, 0.14, 0.48]}
        scale={0.28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16366.geometry}
        material={materials.Phong_FBF058}
        position={[0.02, 0.3, -0.12]}
        rotation={[0.95, -0.48, 1.3]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16365.geometry}
        material={materials.Phong_FBF058}
        position={[0.03, 0.3, -0.12]}
        rotation={[1.87, 0.31, -1.6]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16361.geometry}
        material={materials.Phong_8AB600}
        position={[-0.02, 0.13, -0.06]}
        rotation={[1.53, -0.3, -1.96]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16360.geometry}
        material={materials.Phong_78AC41}
        position={[0.02, 0.11, -0.01]}
        rotation={[1.95, 0.04, 0.45]}
        scale={0.42}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16359.geometry}
        material={materials.Phong_8AB600}
        position={[0.04, 0.13, 0.02]}
        rotation={[1.73, 0.02, 1.38]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16358.geometry}
        material={materials.Phong_8AB600}
        position={[0.05, 0.13, -0.09]}
        rotation={[1.46, -0.46, -0.43]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16357.geometry}
        material={materials.Phong_8AB600}
        position={[-0.04, 0.14, -0.06]}
        rotation={[1.43, 0.26, 1.65]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16353.geometry}
        material={materials.Phong_8AB600}
        position={[-0.01, 0.14, -0.04]}
        rotation={[2.22, 0.43, 0.32]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16352.geometry}
        material={materials.Phong_78AC41}
        position={[0.02, 0.14, -0.08]}
        rotation={[1.51, -0.36, -1.05]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16350.geometry}
        material={materials.Phong_8AB600}
        position={[-0.03, 0.13, -0.07]}
        rotation={[0.71, -0.22, 2.33]}
        scale={0.48}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16349.geometry}
        material={materials.Phong_698A1F}
        position={[0.05, 0.16, -0.03]}
        rotation={[1.72, -0.98, -0.76]}
        scale={0.37}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16343.geometry}
        material={materials.Phong_FBF058}
        position={[0.09, 0.29, -0.15]}
        rotation={[1.45, -1.2, 2.67]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16342.geometry}
        material={materials.Phong_FBF058}
        position={[0.08, 0.3, -0.16]}
        rotation={[2.08, -0.98, -2.52]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16340.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.09, 0.33, 0.02]}
        rotation={[1.6, 0.46, -1.41]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16339.geometry}
        material={materials.Phong_FBF058}
        position={[0.09, 0.29, -0.16]}
        rotation={[1.01, 0.04, -0.22]}
        scale={0.32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16338.geometry}
        material={materials.Phong_FBF058}
        position={[0.09, 0.29, -0.15]}
        rotation={[0.45, -0.31, 0.56]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16337.geometry}
        material={materials.Phong_FBF058}
        position={[0.08, 0.29, -0.16]}
        rotation={[1.89, -0.27, -1.95]}
        scale={0.45}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16335.geometry}
        material={materials.Phong_E4BD17}
        position={[0, 0.3, -0.2]}
        rotation={[1.09, -0.81, 2.48]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16334.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.01, 0.3, -0.2]}
        rotation={[1.7, -0.57, -2.65]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16333.geometry}
        material={materials.Phong_E4BD17}
        position={[0.01, 0.3, -0.22]}
        rotation={[1.53, 0.13, -0.64]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16332.geometry}
        material={materials.Phong_FAF14C}
        position={[0.01, 0.3, -0.2]}
        rotation={[1.26, 0.45, -0.66]}
        scale={0.33}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16331.geometry}
        material={materials.Phong_FAF14C}
        position={[0.01, 0.3, -0.2]}
        rotation={[0.99, -0.58, 1.81]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16330.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.09, 0.35, 0.02]}
        rotation={[1.54, -0.34, -2.78]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16329.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.09, 0.33, 0.01]}
        rotation={[1.84, -0.25, -2.8]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16328.geometry}
        material={materials.Phong_FAF14C}
        position={[0.01, 0.3, -0.2]}
        rotation={[0.78, -0.14, 0.77]}
        scale={0.34}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16327.geometry}
        material={materials.Phong_FBF058}
        position={[-0.07, 0.34, -0.11]}
        rotation={[2.33, 0.25, -1.81]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16326.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.08, 0.34, 0.02]}
        rotation={[0.91, -0.18, 1.5]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16325.geometry}
        material={materials.Phong_FBF058}
        position={[-0.07, 0.33, -0.11]}
        rotation={[1.77, 0.43, -0.99]}
        scale={0.28}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16324.geometry}
        material={materials.Phong_FBF058}
        position={[0.09, 0.29, -0.16]}
        rotation={[1.51, 0.32, -0.93]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16323.geometry}
        material={materials.Phong_FBF058}
        position={[-0.05, 0.33, -0.09]}
        rotation={[0.89, -0.4, 1.73]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16322.geometry}
        material={materials.Phong_FBF058}
        position={[-0.06, 0.33, -0.09]}
        rotation={[1.15, -0.64, 2.38]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16321.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.09, 0.33, 0.01]}
        rotation={[1.06, 0.51, -0.19]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16320.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.08, 0.34, 0.01]}
        rotation={[0.9, 0.47, 0.54]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16318.geometry}
        material={materials.Phong_FBF058}
        position={[-0.06, 0.33, -0.1]}
        rotation={[0.91, 0.42, 0.26]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16317.geometry}
        material={materials.Phong_FBF058}
        position={[-0.06, 0.33, -0.1]}
        rotation={[1.9, -0.14, -3.02]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16315.geometry}
        material={materials.Phong_FBF058}
        position={[0.08, 0.29, 0.03]}
        rotation={[2.64, 0.11, -1.86]}
        scale={0.43}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16314.geometry}
        material={materials.Phong_FBF058}
        position={[0.09, 0.3, 0.03]}
        rotation={[2.46, 0.41, -1.29]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16313.geometry}
        material={materials.Phong_FBF058}
        position={[0.09, 0.29, 0.03]}
        rotation={[1.13, 0.02, 0.66]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16312.geometry}
        material={materials.Phong_FBF058}
        position={[0.08, 0.29, 0.03]}
        rotation={[1.75, 0.4, -0.48]}
        scale={0.45}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16311.geometry}
        material={materials.Phong_E4BD17}
        position={[0.08, 0.29, 0.03]}
        rotation={[1.41, -0.46, 1.35]}
        scale={0.32}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16310.geometry}
        material={materials.Phong_E4BD17}
        position={[0.07, 0.28, 0.03]}
        rotation={[2.02, -0.95, 2.62]}
        scale={0.41}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16302.geometry}
        material={materials.Phong_FAF14C}
        position={[0.18, 0.21, -0.01]}
        rotation={[1.59, 0.21, -0.43]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16301.geometry}
        material={materials.Phong_FAF14C}
        position={[0.18, 0.2, 0.01]}
        rotation={[2.02, -0.64, -3.13]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16299.geometry}
        material={materials.Phong_FAF14C}
        position={[0.18, 0.21, 0.01]}
        rotation={[0.99, -0.58, 1.08]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16298.geometry}
        material={materials.Phong_E4BD17}
        position={[0.18, 0.21, 0]}
        rotation={[2.21, -0.05, -1.43]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16297.geometry}
        material={materials.Phong_FAF14C}
        position={[0.17, 0.2, 0.01]}
        rotation={[2.19, -0.19, -2.09]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16296.geometry}
        material={materials.Phong_E4BD17}
        position={[0.19, 0.22, 0.01]}
        rotation={[1.2, -0.29, 1.39]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16295.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.06, 0.33, -0.18]}
        rotation={[1.24, -0.64, 2.53]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16294.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.07, 0.32, -0.19]}
        rotation={[1.2, 0.32, -0.41]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16292.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.06, 0.32, -0.19]}
        rotation={[1.93, 0.09, -1.93]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16291.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.06, 0.33, -0.18]}
        rotation={[0.68, -0.22, 1.31]}
        scale={0.27}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16290.geometry}
        material={materials.Phong_FAF14C}
        position={[-0.06, 0.32, -0.19]}
        rotation={[0.75, -0.1, 0.67]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16289.geometry}
        material={materials.Phong_E4BD17}
        position={[-0.07, 0.34, -0.19]}
        rotation={[1.72, -0.19, -1.74]}
        scale={0.26}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16216.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.35, 0.09]}
        rotation={[2.98, -0.05, -2.67]}
        scale={0.31}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16215.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.34, 0.1]}
        rotation={[2.28, 0.57, -1.44]}
        scale={0.38}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16214.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.34, 0.1]}
        rotation={[1.57, -0.41, 1.62]}
        scale={0.35}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16212.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.35, 0.09]}
        rotation={[1.6, 0.81, 0.13]}
        scale={0.3}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16211.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.35, 0.09]}
        rotation={[2.72, -0.17, -3.07]}
        scale={0.36}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.n16210.geometry}
        material={materials.Phong_FBF058}
        position={[-0.01, 0.35, 0.1]}
        rotation={[1.57, 0.25, 0.76]}
        scale={0.28}
      />
    </group>
  );
});

useGLTF.preload('/models/SingleTulip.gltf');
